services:
  - type: web
    name: pharmanet-backend
    env: node
    plan: free
    rootDir: back
    buildCommand: npm install
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_NAME
        value: defaultdb
      - key: DB_USER
        value: avnadmin
      - key: DB_PASSWORD
        value: YOUR_AIVEN_PASSWORD_HERE
      - key: DB_HOST
        value: YOUR_AIVEN_HOST_HERE
      - key: DB_PORT
        value: 28221
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: CORS_ORIGIN
        value: https://test-pharma.netlify.app