services:
  - type: web
    name: pharmacie-fidelite-backend
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: pharmacie-fidelite-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://your-frontend-domain.vercel.app

databases:
  - name: pharmacie-fidelite-db
    databaseName: pharmacie_fidelite
    user: pharmacie_user
    plan: free
